[package]
name = "exercices"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fraction = "0.13.1"
rand = "0.8.5"
rust_decimal = "1.31.0"
rust_decimal_macros = "1.31.0"
